spring.h2.console.enabled=true
spring.h2.console.path=/h2-console



spring.cloud.discovery.enabled=true
eureka.client.service-url.defaultZone=${DISCOVERY_SERVICE_URL:http://localhost:8082/eureka}
# On active tous les endPoints de actuator
management.endpoints.web.exposure.include=*
# pour avoir les adresses IP et non pas les noms
eureka.instance.prefer-ip-address=true

info.app.name=My Application
info.app.description=This is a Spring Boot service
info.app.version=1.0.0
info.team.name=My Team
info.team.email=team@example.com

